--活动开启状态的配置  每个项代表一个活动 true 为开启 false为关闭
--配置后请重启服务器 

TasksConfig=
{
	--常规活动
  RobberAttackCity = false,  --怪物袭城 
  MonBoss = true, --世界刷BOSS2
  CampDart = true, --阵营运镖
  one00oneWish = true,  --一千零一个愿望 
  specialMeeting = true, --奇遇系统
	HolyFlameDefend = true,	--圣火保卫战
	
	--阵营活动
	GroupLeaderConquest = true, --阵营军团长争夺战活动 
  GroupMasterAttack = true,   --阵营领袖攻击战活动
	GetCampAwards = true, --阵营俸禄
	CampStatueWorship = true, --阵营雕像膜拜
	
	--节日活动
	MidAutumnFestival = true,	--中秋节活动
	MidAutumnFestival_HuaHaoYueYuan = false, --中秋节活动_花好月圆
	
	--采集蟠桃活动
	GatherPeach = true,
	TianYuan = true,
	
	
}